In [65]:
import numpy as np
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction import DictVectorizer

In [66]:
## Imputing data into missing places
x = [[2,3],[np.NaN,5],[5,2],[7,np.NaN]]
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)

imp.fit_transform(x)

array([[2.        , 3.        ],
       [4.66666667, 5.        ],
       [5.        , 2.        ],
       [7.        , 3.33333333]])

In [62]:
## One hot encoder - 
oneH = OneHotEncoder(n_values=[3,3,4])
oneH.fit([[0,0,3],[1,1,0],[1,2,2]])
oneT = oneH.transform([[0,1,2],[1,0,2]])
oneT.toarray()

array([[1., 0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 1., 0.]])

In [74]:
h2 = OneHotEncoder(n_values=5)
h2.fit([[0]])

print(h2.transform([[1]]).toarray())
h2.fit_transform([[3]]).toarray()

[[0. 1. 0. 0. 0.]]


array([[0., 0., 0., 1., 0.]])

In [89]:
## Dict vectorizer- mainly used for extracting feature from sting type features
dicVal = [{'city': 'Dubai', 'temp': 12, 'col': 'red', 'stat': 'High'}, 
          {'city':'mumbai', 'temp': 23, 'col': 'yel', 'stat': 'Med'}, 
          {'city': 'Ny', 'temp': 45, 'col': 'blu', 'stat': 'High'}, 
          {'city': 'london', 'temp': 34, 'col': 'mar', 'stat': 'Med'},
          {'city': 'Dubai', 'temp': 56, 'col': 'whi', 'stat': 'Med'}]
dic = DictVectorizer()
dic.fit_transform(dicVal).toarray()

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0., 12.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  1., 23.],
       [ 0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0., 45.],
       [ 0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1., 34.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1., 56.]])

In [86]:
dic.fit(dicVal)
dic.fit_transform([{'city':'Dubai'}]).toarray()

array([[1.]])

In [87]:
dic.fit_transform([{'city':''}]).toarray()

array([[1.]])